<?php

namespace System\Foundation\Oops;

defined('DS') or exit('No direct access.');

$code = $e->getCode() ? ' #' . $e->getCode() : '';
?>
<div id="oops-panic">
    <a id="oops-panic-toggle" href="#" class="oops-toggle"></a>
    <div>
        <div id="oops-panic-error" class="panel">
            <?php if ($e->getMessage()) : ?>
                <p><?php echo Helpers::escapeHtml($title . $code) ?></p>
            <?php endif ?>

            <h1>
                <span><?php echo $messageHtml ?: Helpers::escapeHtml($title . $code) ?></span>
                <?php foreach ($actions as $item) : ?>
                    <a href="<?php echo Helpers::escapeHtml($item['link']) ?>" <?php echo empty($item['external']) ? '' : ' target="_blank" rel="noreferrer noopener"' ?>><?php echo Helpers::escapeHtml($item['label']) ?>&#x25ba;</a>
                <?php endforeach ?>
            </h1>
        </div>

        <?php if ($prev = $e->getPrevious()) : ?>
            <div class="caused">
                <a href="#oopsCaused">Caused by <?php echo Helpers::escapeHtml(Helpers::getClass($prev)) ?></a>
            </div>
        <?php endif ?>


        <?php
        $ex = $e;
        $level = 0;
        ?>
        <?php do { ?>

            <?php if ($level++) : ?>
                <div class="panel" <?php if (2 === $level) echo ' id="oopsCaused"' ?>>
                    <h2><a data-oops-ref="^+" class="oops-toggle<?php echo ($collapsed = $level > 2) ? ' oops-collapsed' : '' ?>">Caused by</a></h2>

                    <div class="<?php echo $collapsed ? 'oops-collapsed ' : '' ?>inner">
                        <div class="panel">
                            <h2><?php echo Helpers::escapeHtml(Helpers::getClass($ex) . ($ex->getCode() ? ' #' . $ex->getCode() : '')) ?></h2>

                            <h2><?php echo Helpers::escapeHtml($ex->getMessage()) ?></h2>
                        </div>
                    <?php endif ?>

                    <?php foreach ($this->renderPanels($ex) as $panel) : ?>
                        <div class="panel">
                            <h2><a data-oops-ref="^+" class="oops-toggle"><?php echo Helpers::escapeHtml($panel->tab) ?></a></h2>

                            <div class="inner">
                                <?php echo $panel->panel ?>
                            </div>
                        </div>
                    <?php endforeach ?>


                    <?php $stack = $ex->getTrace();
                    $expanded = null ?>
                    <?php if ((!($e instanceof \ErrorException) || in_array($e->getSeverity(), [E_USER_NOTICE, E_USER_WARNING, E_USER_DEPRECATED], true)) && $this->isCollapsed($ex->getFile())) {
                        foreach ($stack as $key => $row) {
                            if (isset($row['file']) && !$this->isCollapsed($row['file'])) {
                                $expanded = $key;
                                break;
                            }
                        }
                    } ?>

                    <div class="panel">
                        <h2><a data-oops-ref="^+" class="oops-toggle<?php echo ($collapsed = $expanded !== null) ? ' oops-collapsed' : '' ?>">Source file</a></h2>

                        <div class="<?php echo $collapsed ? 'oops-collapsed ' : '' ?>inner">
                            <p><b>File:</b> <?php echo Helpers::editorLink($ex->getFile(), $ex->getLine()) ?></p>
                            <?php if (is_file($ex->getFile())) : ?>
                                <?php $ctx = (\ErrorException::class === get_class($ex) || $ex instanceof \ErrorException) ? \System\Foundation\Oops\Context::getContext($ex) : null; ?>
                                <?php echo self::highlightFile($ex->getFile(), $ex->getLine(), 15, is_array($ctx) ? $ctx : null) ?>
                            <?php endif ?>
                        </div>
                    </div>

                    <?php if (isset($stack[0]['class']) && 'System\Foundation\Oops\Debugger' === $stack[0]['class'] && ('shutdownHandler' === $stack[0]['function'] || 'errorHandler' === $stack[0]['function'])) unset($stack[0]) ?>
                    <?php if ($stack) : ?>
                        <div class="panel">
                            <h2><a data-oops-ref="^+" class="oops-toggle">Call stack</a></h2>

                            <div class="inner">
                                <ol>
                                    <?php foreach ($stack as $key => $row) : ?>
                                        <li>
                                            <p>
                                                <?php if (isset($row['file']) && is_file($row['file'])) : ?>
                                                    <?php echo Helpers::editorLink($row['file'], $row['line']) ?>
                                                <?php else : ?>
                                                    <i>inner-code</i><?php if (isset($row['line'])) echo ':', $row['line'] ?>
                                                <?php endif ?>

                                                <?php if (isset($row['file']) && is_file($row['file'])) : ?><a data-oops-ref="^p + .file" class="oops-toggle<?php if ($expanded !== $key) echo ' oops-collapsed' ?>">source</a>&nbsp; <?php endif ?>

                                                <?php
                                                if (isset($row['object'])) echo "<a data-oops-ref='^p + .object' class='oops-toggle oops-collapsed'>";
                                                if (isset($row['class'])) echo Helpers::escapeHtml($row['class'] . $row['type']);
                                                if (isset($row['object'])) echo '</a>';
                                                echo Helpers::escapeHtml($row['function']), '(';
                                                if (!empty($row['args'])) : ?><a data-oops-ref="^p + .args" class="oops-toggle oops-collapsed">arguments</a><?php endif ?>)
                                            </p>

                                            <?php if (isset($row['file']) && is_file($row['file'])) : ?>
                                                <div class="<?php if ($expanded !== $key) echo 'oops-collapsed ' ?>file"><?php echo self::highlightFile($row['file'], $row['line']) ?></div>
                                            <?php endif ?>

                                            <?php if (isset($row['object'])) : ?>
                                                <div class="oops-collapsed outer object"><?php echo $dump($row['object']) ?></div>
                                            <?php endif ?>

                                            <?php if (!empty($row['args'])) : ?>
                                                <div class="oops-collapsed outer args">
                                                    <table>
                                                        <?php
                                                        try {
                                                            $r = isset($row['class'])
                                                                ? new  \ReflectionMethod($row['class'], $row['function'])
                                                                : new \ReflectionFunction($row['function']);
                                                            $params = $r->getParameters();
                                                        } catch (\Throwable $e) {
                                                            $params = [];
                                                        } catch (\Exception $e) {
                                                            $params = [];
                                                        }

                                                        foreach ($row['args'] as $k => $v) {
                                                            echo '<tr><th>', Helpers::escapeHtml(isset($params[$k]) ? '$' . $params[$k]->name : "#$k"), '</th><td>';
                                                            echo $dump($v, isset($params[$k]) ? $params[$k]->name : null);
                                                            echo "</td></tr>\n";
                                                        }
                                                        ?>
                                                    </table>
                                                </div>
                                            <?php endif ?>
                                        </li>
                                    <?php endforeach ?>
                                </ol>
                            </div>
                        </div>
                    <?php endif ?>

                    <?php $vars = (\ErrorException::class === get_class($ex) || $ex instanceof \ErrorException) ? \System\Foundation\Oops\Context::getContext($ex) : null; ?>
                    <?php if (is_array($vars) && $vars) : ?>
                        <div class="panel">
                            <h2><a data-oops-ref="^+" class="oops-toggle oops-collapsed">Variables</a></h2>

                            <div class="oops-collapsed inner">
                                <div class="outer">
                                    <table>
                                        <?php
                                        foreach ($vars as $k => $v) {
                                            echo '<tr><th>$', Helpers::escapeHtml($k), '</th><td>', $dump($v, $k), "</td></tr>\n";
                                        }
                                        ?>
                                    </table>
                                </div>
                            </div>
                        </div>
                    <?php endif ?>

                <?php } while ($ex = $ex->getPrevious()); ?>
                <?php while (--$level) echo '</div></div>' ?>

                <?php if (count((array) $e) > count((array) new \Exception())) : ?>
                    <div class="panel">
                        <h2><a data-oops-ref="^+" class="oops-toggle oops-collapsed">Exception</a></h2>
                        <div class="oops-collapsed inner">
                            <?php echo $dump($e) ?>
                        </div>
                    </div>
                <?php endif ?>

                <?php if ($lastError) : ?>
                    <div class="panel">
                        <h2><a data-oops-ref="^+" class="oops-toggle oops-collapsed">Last muted error</a></h2>
                        <div class="oops-collapsed inner">
                            <h3><?php echo Helpers::errorTypeToString($lastError['type']) ?>: <?php echo Helpers::escapeHtml($lastError['message']) ?></h3>
                            <?php if (isset($lastError['file']) && is_file($lastError['file'])) : ?>
                                <p>
                                <div>
                                    <?php echo self::highlightFile($lastError['file'], $lastError['line']) ?>
                                </div>
                            <?php else : ?>
                                <p><i>inner-code</i><?php if (isset($lastError['line'])) echo ':', $lastError['line'] ?></p>
                            <?php endif ?>

                        </div>
                    </div>
                <?php endif ?>

                <?php $bottomPanels = [] ?>
                <?php foreach ($this->renderPanels(null) as $panel) : ?>
                    <?php if (!empty($panel->bottom)) {
                        $bottomPanels[] = $panel;
                        continue;
                    } ?>
                    <?php $collapsedClass = !isset($panel->collapsed) || $panel->collapsed ? ' oops-collapsed' : ''; ?>
                    <div class="panel">
                        <h2><a data-oops-ref="^+" class="oops-toggle<?php echo $collapsedClass ?>"><?php echo Helpers::escapeHtml($panel->tab) ?></a></h2>
                        <div class="inner<?php echo $collapsedClass ?>">
                            <?php echo $panel->panel ?>
                        </div>
                    </div>
                <?php endforeach ?>

                <div class="panel">
                    <h2><a data-oops-ref="^+" class="oops-toggle oops-collapsed">Environment</a></h2>
                    <div class="oops-collapsed inner">
                        <h3><a data-oops-ref="^+" class="oops-toggle">$_SERVER</a></h3>
                        <div class="outer">
                            <table>
                                <?php
                                foreach ($_SERVER as $k => $v) echo '<tr><th>', Helpers::escapeHtml($k), '</th><td>', $dump($v, $k), "</td></tr>\n";
                                ?>
                            </table>
                        </div>

                        <h3><a data-oops-ref="^+" class="oops-toggle">$_SESSION</a></h3>
                        <div class="outer">
                            <?php if (empty($_SESSION)) : ?>
                                <p><i>empty</i></p>
                            <?php else : ?>
                                <table>
                                    <?php
                                    foreach ($_SESSION as $k => $v) echo '<tr><th>' . Helpers::escapeHtml($k) . '</th><td>' . (('__RF' === $k) ? '<i>Rakit Session</i>' : $dump($v, $k)) . "</td></tr>\n";
                                    ?>
                                </table>
                            <?php endif ?>
                        </div>

                        <?php if (!empty($_SESSION['__RF']['DATA'])) : ?>
                            <h3><a data-oops-ref="^+" class="oops-toggle">Rakit Session</a></h3>
                            <div class="outer">
                                <table>
                                    <?php
                                    foreach ($_SESSION['__RF']['DATA'] as $k => $v) echo '<tr><th>', Helpers::escapeHtml($k), '</th><td>', $dump($v, $k), "</td></tr>\n";
                                    ?>
                                </table>
                            </div>
                        <?php endif ?>

                        <?php
                        $list = get_defined_constants(true);
                        if (!empty($list['user'])) : ?>
                            <h3><a data-oops-ref="^+" class="oops-toggle oops-collapsed">Constants</a></h3>
                            <div class="outer oops-collapsed">
                                <table>
                                    <?php
                                    foreach ($list['user'] as $k => $v) {
                                        echo '<tr><th>', Helpers::escapeHtml($k), '</th>';
                                        echo '<td>', $dump($v, $k), "</td></tr>\n";
                                    }
                                    ?>
                                </table>
                            </div>
                        <?php endif ?>

                        <h3><a data-oops-ref="^+" class="oops-toggle oops-collapsed">Configuration options</a></h3>
                        <div class="outer oops-collapsed">
                            <?php $this->renderPhpInfo() ?>
                        </div>
                    </div>
                </div>

                <div class="panel">
                    <h2><a data-oops-ref="^+" class="oops-toggle oops-collapsed">HTTP request</a></h2>
                    <div class="oops-collapsed inner">
                        <?php if (function_exists('apache_request_headers')) : ?>
                            <h3>Headers</h3>
                            <div class="outer">
                                <table>
                                    <?php
                                    foreach (apache_request_headers() as $k => $v) echo '<tr><th>', Helpers::escapeHtml($k), '</th><td>', Helpers::escapeHtml($v), "</td></tr>\n";
                                    ?>
                                </table>
                            </div>
                        <?php endif ?>

                        <?php foreach (['_GET', '_POST', '_COOKIE'] as $name) : ?>
                            <h3>$<?php echo Helpers::escapeHtml($name) ?></h3>
                            <?php if (empty($GLOBALS[$name])) : ?>
                                <p><i>empty</i></p>
                            <?php else : ?>
                                <div class="outer">
                                    <table>
                                        <?php
                                        foreach ($GLOBALS[$name] as $k => $v) echo '<tr><th>', Helpers::escapeHtml($k), '</th><td>', $dump($v, $k), "</td></tr>\n";
                                        ?>
                                    </table>
                                </div>
                            <?php endif ?>
                        <?php endforeach ?>
                    </div>
                </div>

                <div class="panel">
                    <h2><a data-oops-ref="^+" class="oops-toggle oops-collapsed">HTTP response</a></h2>
                    <div class="oops-collapsed inner">
                        <h3>Headers</h3>
                        <?php if (headers_list()) : ?>
                            <pre><?php foreach (headers_list() as $s) echo Helpers::escapeHtml($s), '<br>'; ?></pre>
                        <?php else : ?>
                            <p><i>no headers</i></p>
                        <?php endif ?>
                    </div>
                </div>

                <?php foreach ($bottomPanels as $panel) : ?>
                    <div class="panel">
                        <h2><a data-oops-ref="^+" class="oops-toggle"><?php echo Helpers::escapeHtml($panel->tab) ?></a></h2>

                        <div class="inner">
                            <?php echo $panel->panel ?>
                        </div>
                    </div>
                <?php endforeach ?>

                <ul>
                    <li>Report generated at <?php echo @date('Y/m/d H:i:s'); ?></li>
                    <li><?php if ($sourceIsUrl) : ?><a href="<?php echo Helpers::escapeHtml($source) ?>"><?php endif ?><?php echo Helpers::escapeHtml($source) ?><?php if ($sourceIsUrl) : ?></a><?php endif ?></li>
                    <?php foreach ($info as $item) : ?><li><?php echo Helpers::escapeHtml($item) ?></li><?php endforeach ?>
                </ul>

                <div id="oops-panic-logo"></div>
                    </div>
                </div>
