<?php

namespace System\Foundation\Oops;

defined('DS') or exit('No direct script access.');

$code = $e->getCode() ? ' #'.$e->getCode() : '';
$nonceAttr = $nonce ? ' nonce="'.Helpers::escapeHtml($nonce).'"' : '';
?><!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></iframe></noembed></noframes></noscript></option></select></template></title></table>
<html>
<head>
	<meta charset="utf-8">
	<meta name="robots" content="noindex">
	<meta name="generator" content="Rakit debugger">

	<title><?php echo Helpers::escapeHtml($title.': '.$e->getMessage().$code) ?></title>
	<?php if ($ex = $e->getPrevious()): ?>
<!--<?php do { echo str_replace('--', '- ', Helpers::escapeHtml("\n\tcaused by ".Helpers::getClass($ex).': '.$ex->getMessage().($ex->getCode() ? ' #'.$ex->getCode() : ''))); } while ($ex = $ex->getPrevious()); ?> -->
	<?php endif ?>

	<style type="text/css" class="oops-debug">
	<?php echo str_replace('</', '<\/', $css) ?>
	</style>
	<script<?php echo $nonceAttr ?>>document.documentElement.className += ' oops-js'</script>
</head>


<body>
<?php require __DIR__.DS.'content.phtml' ?>

<script<?php echo $nonceAttr ?>>
(function() {
	<?php readfile(dirname(__DIR__).DS.'toggle'.DS.'toggle.js') ?>
	<?php readfile(dirname(__DIR__).DS.'dumper'.DS.'dumper.js') ?>
	<?php readfile(__DIR__.DS.'panic.js') ?>
})();
</script>
<script<?php echo $nonceAttr ?>>
Oops && Oops.Dumper.init(<?php echo str_replace('<!--', '<\!--', json_encode(Dumper::fetchLiveData())) ?>);
</script>
<script<?php echo $nonceAttr ?>>
Oops && Oops.Panic.init();
</script>
</body>
</html>
