<?php

namespace System\Foundation\Oops;

defined('DS') or exit('No direct script access.');

if (empty($data)) {
    return;
}
?>
<style class="oops-debug">
    #oops-debug .oops-ErrorTab {
        display: block;
        background: #D51616;
        color: white;
        font-weight: bold;
        margin: -1px -.4em;
        padding: 1px .4em;
    }
</style>
<span class="oops-ErrorTab">
    <svg id="i-alert" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
        <path d="M16 3 L30 29 2 29 Z M16 11 L16 19 M16 23 L16 25" />
    </svg>
    <span class="oops-label">
        <?php echo $sum = array_sum($data), $sum > 1 ? ' errors' : ' error' ?>
    </span>
