<?php

namespace System\Foundation\Oops;

defined('DS') or exit('No direct access.');
?>
<h1>Errors</h1>

<div class="oops-inner">
    <table>
        <?php foreach ($data as $item => $count) : list($file, $line, $message) = explode('|', $item, 3) ?>
            <tr>
                <td class="oops-right"><?php echo $count ? "$count\xC3\x97" : '' ?></td>
                <td>
                    <pre><?php echo Helpers::escapeHtml($message), ' in ', '<span>', $file . ($line ? ":$line" : ''), '</span>' ?></pre>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
</div>
