<?php

namespace System\Foundation\Oops;

defined('DS') or exit('No direct access.');

if (isset($this->cpuUsage) && $this->time) {
    foreach (getrusage() as $key => $val) {
        $this->cpuUsage[$key] -= $val;
    }

    $userUsage = -round(($this->cpuUsage['ru_utime.tv_sec'] * 1e6 + $this->cpuUsage['ru_utime.tv_usec']) / $this->time / 10000);
    $systemUsage = -round(($this->cpuUsage['ru_stime.tv_sec'] * 1e6 + $this->cpuUsage['ru_stime.tv_usec']) / $this->time / 10000);
}

$countClasses = function ($list) {
    return count(array_filter($list, function ($name) {
        return (new \ReflectionClass($name))->isUserDefined();
    }));
};

$opcache = function_exists('opcache_get_status') ? @opcache_get_status() : null; // @ can be restricted
$cachedFiles = isset($opcache['scripts']) ? array_intersect(array_keys($opcache['scripts']), get_included_files()) : [];

$info = [
    'Execution time' => number_format($this->time * 1000, 1, '.', ' ') . ' ms',
    'CPU usage user + system' => isset($userUsage) ? (int) $userUsage . ' % + ' . (int) $systemUsage . ' %' : null,
    'Peak of allocated memory' => number_format(memory_get_peak_usage() / 1000000, 2, '.', ' ') . ' MB',
    'Included files' => count(get_included_files()),
    'OPcache' => $opcache ? round(count($cachedFiles) * 100 / count(get_included_files())) . '% cached' : null,
    'Classes + interfaces + traits' => $countClasses(get_declared_classes()) . ' + '
        . $countClasses(get_declared_interfaces()) . ' + ' . $countClasses(get_declared_traits()),
    'Your IP' => isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : null,
    'Server IP' => isset($_SERVER['SERVER_ADDR']) ? $_SERVER['SERVER_ADDR'] : null,
    'HTTP method / response code' => isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] . ' / ' . http_response_code() : null,
    'PHP' => PHP_VERSION,
    'Xdebug' => extension_loaded('xdebug') ? phpversion('xdebug') : null,
    'Framework version' => RAKIT_VERSION,
    'Server' => isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : null,
];

$info = array_map('strval', array_filter($info + (array) $this->data));

$packages = $devPackages = [];
if (class_exists('Composer\Autoload\ClassLoader', false)) {
    $baseDir = call_user_func(function () {
        @include dirname((new \ReflectionClass('Composer\Autoload\ClassLoader'))->getFileName()) . '/autoload_psr4.php';
        return $baseDir;
    });
    $composer = @json_decode(file_get_contents($baseDir . '/composer.lock'));
    list($packages, $devPackages) = [(array) @$composer->packages, (array) @$composer->{'packages-dev'}];
    $tmp = [&$packages, &$devPackages];
    foreach ($tmp as &$items) {
        @array_walk($items, function ($package) {
            $package->hash = $package->source->reference ? $package->source->reference : $package->dist->reference;
        }, $items);
        usort($items, function ($a, $b) {
            return strcmp($a->name, $b->name);
        });
    }
}

?>
<style class="oops-debug">
    #oops-debug .oops-InfoPanel td {
        white-space: nowrap;
    }

    #oops-debug .oops-InfoPanel td:nth-child(2) {
        font-weight: bold;
        width: 30%;
    }

    #oops-debug .oops-InfoPanel td[colspan='2'] b {
        float: right;
        margin-left: 2em;
    }
</style>

<h1>System info</h1>

<div class="oops-inner oops-InfoPanel">
    <div class="oops-inner-container">
        <table>
            <?php foreach ($info as $key => $val) : ?>
                <tr>
                    <?php if (strlen($val) > 25) : ?>
                        <td colspan=2><?php echo Helpers::escapeHtml($key) ?> <b><?php echo Helpers::escapeHtml($val) ?></b></td>
                    <?php else : ?>
                        <td><?php echo Helpers::escapeHtml($key) ?></td>
                        <td><?php echo Helpers::escapeHtml($val) ?></td>
                    <?php endif ?>
                </tr>
            <?php endforeach ?>
        </table>

        <?php if ($packages || $devPackages) : ?>
            <h2><a class="oops-toggle oops-collapsed" data-oops-ref="^div .oops-InfoPanel-packages">Composer Packages (<?php echo count($packages), $devPackages ? ' + ' . count($devPackages) . ' dev' : '' ?>)</a></h2>

            <div class="oops-InfoPanel-packages oops-collapsed">
                <?php if ($packages) : ?>
                    <table>
                        <?php foreach ($packages as $package) : ?>
                            <tr>
                                <td><?php echo Helpers::escapeHtml($package->name) ?></td>
                                <td><?php echo Helpers::escapeHtml($package->version . (strpos($package->version, 'dev') !== false && $package->hash ? ' #' . substr($package->hash, 0, 4) : '')) ?></td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                <?php endif ?>

                <?php if ($devPackages) : ?>
                    <h2>Dev Packages</h2>
                    <table>
                        <?php foreach ($devPackages as $package) : ?>
                            <tr>
                                <td><?php echo Helpers::escapeHtml($package->name) ?></td>
                                <td><?php echo Helpers::escapeHtml($package->version . (strpos($package->version, 'dev') !== false && $package->hash ? ' #' . substr($package->hash, 0, 4) : '')) ?></td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                <?php endif ?>
            </div>
        <?php endif ?>
    </div>
</div>
