#!/usr/bin/env php
<?php

// --------------------------------------------------------------
// Catat timer awal (untuk benchmark)
// --------------------------------------------------------------
define('RAKIT_START', microtime(true));

// --------------------------------------------------------------
// Definisikan konstanta untuk directory separator.
// --------------------------------------------------------------
define('DS', DIRECTORY_SEPARATOR);

// --------------------------------------------------------------
// Include konstanta path milik framework.
// --------------------------------------------------------------
require 'paths.php';

// --------------------------------------------------------------
// Bootstrap file core milik framework.
// --------------------------------------------------------------
require path('system').'core.php';

// --------------------------------------------------------------
// Pastikan script dijalankan via console.
// --------------------------------------------------------------
is_cli() or exit('Please run this script from your console.');

// --------------------------------------------------------------
// Panggil consolenya.
// --------------------------------------------------------------
require path('system').'console'.DS.'boot.php';
