<?php

namespace System\Foundation\Oops;

defined('DS') or exit('No direct script access.');

?>
<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<meta name="generator" content="Rakit debugger">
<link rel="icon" type="image/png" href="data:;base64,iVBORw0KGgo=">
<title>500 | Internal Server Error</title>

<style>
    #oops-error {
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        min-height: 95vh;
        color: #a0aec0;
        color: rgba(160, 174, 192, 1);
        font-size: 1.125em;
        text-transform: uppercase;
    }
</style>

<div id="oops-error">
    500 | Internal Server Error
</div>

<script>
    document.body.insertBefore(document.getElementById('oops-error'), document.body.firstChild);
</script>
