<?php defined('DS') or exit('No direct script access.'); ?>
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">
    <meta name="generator" content="Rakit debugger">
    <link rel="icon" type="image/png" href="data:;base64,iVBORw0KGgo=">
    <title>500 | Rakit Key Too Short</title>
    <style>
        html, body {
            height: 100%;
            font-family: BlinkMacSystemFont, -apple-system, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
        body {
            margin: 0;
        }
        #oops-error {
            height: 100%;
            padding: 0;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        #row {
            width: auto;
        }
        #oops-error-item {
            text-align: center;
            color: #a0aec0;
            color: rgba(160, 174, 192, 1);
            font-size: 1.125em;
        }
        a, a:visited {
            color: #007bff;
        }
        p#hints {
            margin-top: 20px;
            font-size: 0.9em;
        }
        code, span {
            font-family: Consolas, "Andale Mono WT", "Andale Mono", "Lucida Console", "Lucida Sans Typewriter", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Liberation Mono", "Nimbus Mono L", "Courier New", Courier, monospace;
        }
        span {
            font-family: monospace;
            color: hsl(348, 100%, 61%);
        }
        code {
            background-color: ##f6f8fa;
            border: 1px solid #E7E7E7;
            margin-top: 8px;
            padding: 10px;
            color: hsl(348, 100%, 61%);
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div id="oops-error">
        <div id="row">
            <div id="oops-error-item">500 | RAKIT KEY TOO SHORT</div>
            <div id="oops-error-item">
                <p id="hints">
                    <br>
                    Use this key if you don't have one:
                    <br>
                    <br>
                    <code>
                        <?php echo bin2hex(openssl_random_pseudo_bytes(rand(5, 10))); ?>
                    </code>
                </p>
            </div>
        </div>
    </div>
</body>
</html>
