<?php

namespace System;

defined('DS') or exit('No direct script access.');

/*
|--------------------------------------------------------------------------
| Buat / Baca Rakit Key
|--------------------------------------------------------------------------
| Pastikan file key.php sudah ada di base path, buat jika belum ada.
*/

if (is_file($path = path('rakit_key'))) {
    if (! is_readable(dirname($path))) {
        http_response_code(500);
        require path('system').'foundation'.DS.'oops'.DS.'assets'.DS.'debugger'.DS.'key'.DS.'unreadable.phtml';

        if (function_exists('fastcgi_finish_request')) {
            fastcgi_finish_request();
        }
        exit;
    }

    if (strlen((string) $path) < 10) {
        http_response_code(500);
        require path('system').'foundation'.DS.'oops'.DS.'assets'.DS.'debugger'.DS.'key'.DS.'too-short.phtml';

        if (function_exists('fastcgi_finish_request')) {
            fastcgi_finish_request();
        }
        exit;
    }
} else {
    $path = path('rakit_key');

    if (! is_writable(dirname($path))) {
        http_response_code(500);
        require path('system').'foundation'.DS.'oops'.DS.'assets'.DS.'debugger'.DS.'key'.DS.'unwritable.phtml';

        if (function_exists('fastcgi_finish_request')) {
            fastcgi_finish_request();
        }
        exit;
    }

    try {
        $key = substr(str_shuffle(
            str_repeat('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', 1)
        ), 1, 10);

        file_put_contents(
            path('rakit_key'),
            '<?php'.PHP_EOL.PHP_EOL
            .'defined(\'DS\') or exit(\'No direct script access.\');'.PHP_EOL.PHP_EOL
            .'// AUTO-GENERATED BY RAKIT. DO NOT TOUCH !!'.PHP_EOL
            .sprintf('return \'%s\';', $key).PHP_EOL
        );
    } catch (\Throwable $e) {
        require path('system').'foundation'.DS.'oops'.DS.'assets'.DS.'debugger'.DS.'key'.DS.'unwritable.phtml';

        if (function_exists('fastcgi_finish_request')) {
            fastcgi_finish_request();
        }
        exit;
    } catch (\Exception $e) {
        http_response_code(500);
        require path('system').'foundation'.DS.'oops'.DS.'assets'.DS.'debugger'.DS.'key'.DS.'unwritable.phtml';

        if (function_exists('fastcgi_finish_request')) {
            fastcgi_finish_request();
        }
        exit;
    }
}
