<?php

namespace System;

defined('DS') or exit('No direct script access.');

/*
|--------------------------------------------------------------------------
| Buat / Baca Rakit Key
|--------------------------------------------------------------------------
| Pastikan file key.php sudah ada di base path, buat jika belum ada.
*/

switch (true) {
    case (is_file(path('rakit_key')) && ! is_readable(path('rakit_key'))):
        http_response_code(500);
        require path('system').'foundation'.DS.'oops'.DS.'assets'.DS.'debugger'.DS.'key'.DS.'unreadable.phtml';

        if (function_exists('fastcgi_finish_request')) {
            fastcgi_finish_request();
        }
        exit;

    case (is_file(path('rakit_key')) && strlen((string) require path('rakit_key')) < 10):
        http_response_code(500);
        require path('system').'foundation'.DS.'oops'.DS.'assets'.DS.'debugger'.DS.'key'.DS.'too-short.phtml';

        if (function_exists('fastcgi_finish_request')) {
            fastcgi_finish_request();
        }
        exit;

    case (! is_file(path('rakit_key'))):
        try {
            $rakit_key = substr(str_shuffle(
                str_repeat('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', 1)
            ), 1, 32);

            file_put_contents(
                path('rakit_key'),
                '<?php'.PHP_EOL.PHP_EOL
                .'defined(\'DS\') or exit(\'No direct script access.\');'.PHP_EOL.PHP_EOL
                .'// AUTO-GENERATED BY RAKIT. DO NOT TOUCH !!'.PHP_EOL
                .sprintf('return \'%s\';', $rakit_key).PHP_EOL
            );
        } catch (\Throwable $e) {
            http_response_code(500);
            require path('system').'foundation'.DS.'oops'.DS.'assets'.DS.'debugger'.DS.'key'.DS.'unwritable.phtml';

            if (function_exists('fastcgi_finish_request')) {
                fastcgi_finish_request();
            }
            exit;
        } catch (\Exception $e) {
            http_response_code(500);
            require path('system').'foundation'.DS.'oops'.DS.'assets'.DS.'debugger'.DS.'key'.DS.'unwritable.phtml';

            if (function_exists('fastcgi_finish_request')) {
                fastcgi_finish_request();
            }
            exit;
        }

    default: break;
}
