<?php

namespace System\Console\Commands;

defined('DS') or exit('No direct script access.');

class Key extends Command
{
    /**
     * Path ke file konfigurasi.
     *
     * @var string
     */
    protected $path;

    /**
     * Buta instance baru.
     *
     * @return void
     */
    public function __construct()
    {
        $this->path = path('app').'config'.DS.'application.php';
    }

    /**
     * Isi secret key aplikasi (jika belum terisi).
     *
     * @return void
     */
    public function generate()
    {
        switch (true) {
            case (is_file(path('rakit_key')) && ! is_readable(path('rakit_key'))):
                echo 'Rakit key exists but unreadable.';
                break;

            case (is_file(path('rakit_key')) && strlen((string) require path('rakit_key')) < 10):
                echo 'Rakit key too short, at least 10 characters long.';
                break;

            case (! is_file(path('rakit_key'))):
                try {
                    $rakit_key = substr(str_shuffle(
                        str_repeat('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', 1)
                    ), 1, 10);

                    file_put_contents(
                        path('rakit_key'),
                        '<?php'.PHP_EOL.PHP_EOL
                        .'defined(\'DS\') or exit(\'No direct script access.\');'.PHP_EOL.PHP_EOL
                        .'// AUTO-GENERATED BY RAKIT. DO NOT TOUCH !!'.PHP_EOL
                        .sprintf('return \'%s\';', $rakit_key).PHP_EOL
                    );
                } catch (\Throwable $e) {
                    echo 'Unable to generate key: directory unwritable.';
                    break;
                } catch (\Exception $e) {
                    echo 'Unable to generate key: directory unwritable.';
                    break;
                }

            default:
                echo 'Rakit key already exists';
                break;
        }
    }
}
