<?php

defined('DS') or exit('No direct script access.');

return [
    /*
    |--------------------------------------------------------------------------
    | Home Language
    |--------------------------------------------------------------------------
    |
    | Baris - baris bahasa berikut ini digunakan untuk lokalisasi homepage
    |
    */

    'title' => 'Welcome to Rakit!',
    'slogan' => 'A simple, lightweight and modular PHP framework.',
    'about' => [
        'heading' => 'About this page',
        'text1' => 'The page you are viewing is dynamically generated by rakit. If you want to edit this page, you will find it at:',
        'text2' => 'And the route that handles this page can be found at:',
    ],
    'docs' => [
        'heading' => 'Go further',
        'text' => 'The documentation page contains introductions, tutorials and feature references. Feel free to start reading the :documentation that can open it both online and offline.',
    ],
    'resources' => [
        'heading' => 'Create something beautiful!',
        'text' => "Now that the installation is running, it's time to start creating! Here are some links to help you get started:",
    ],
    'links' => [
        'site' => 'Official Site',
        'api' => 'API Reference',
        'repos' => 'Package Repository',
        'forum' => 'Discussion Forum',
        'source' => 'Source Code',
    ],
    'documentation' => 'documentation',
];
